package com.zb.bilateral.dbHelper;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zb.bilateral.model.SearchModel;

import com.zb.bilateral.dbHelper.SearchModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchModelDaoConfig;

    private final SearchModelDao searchModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchModelDaoConfig = daoConfigMap.get(SearchModelDao.class).clone();
        searchModelDaoConfig.initIdentityScope(type);

        searchModelDao = new SearchModelDao(searchModelDaoConfig, this);

        registerDao(SearchModel.class, searchModelDao);
    }
    
    public void clear() {
        searchModelDaoConfig.clearIdentityScope();
    }

    public SearchModelDao getSearchModelDao() {
        return searchModelDao;
    }

}
